name: 2.7.4 Upgrade to Nightly
on:
  workflow_dispatch: {}

  schedule:
    - cron: "40 5 * * *"

jobs:
  test:
    strategy:
      matrix:
        go: [1.18]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Install Dependencies
        shell: bash
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Create On 2.7.4 Release
        shell: bash
        run: |
          cat docker-compose.template | \
          sed -e "s+{{IMAGE}}+nats:2.7.4-alpine+g" | \
          sed -e "s+{{CONFIG}}+/etc/nats/nats-server.conf+g" > docker-compose.yaml
          
          docker compose up -d --quiet-pull

          SKIP_RELOCATION=1 SKIP_REPLICAS=1 ginkgo --after-run-hook="docker compose logs" --keep-going -vet=off -r suites

      - name: Validate Today Nightly
        shell: bash
        run: |
          NIGHTLY=$(date +%Y%m%d)
          cat docker-compose.template | \
          sed -e "s+{{IMAGE}}+synadia/nats-server:nightly-${NIGHTLY}+g" | \
          sed -e "s+{{CONFIG}}+/nats/conf/nats-server.conf+g" > docker-compose.yaml
          
          docker compose up -d --quiet-pull

          VALIDATE_ONLY=1 SKIP_RELOCATION=1 SKIP_REPLICAS=1 ginkgo --after-run-hook="docker compose logs" --keep-going -vet=off -r suites
