name: Integration Tests
on:
  workflow_dispatch: {}

  schedule:
    - cron: "40 5 * * *"

jobs:
  test:
    strategy:
      matrix:
        go: [1.18]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Create On Yesterday
        shell: bash
        run: |
          NIGHTLY=$(date --date="yesterday" +%Y%m%d)
          cat docker-compose.template|sed -e "s+{{IMAGE}}+synadia/nats-server:nightly-${NIGHTLY}+g" > docker-compose.yaml
          
          docker compose up -d

          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          ginkgo -v --keep-going -vet=off -r suites

      - name: Validate Today
        shell: bash
        run: |
          NIGHTLY=$(date +%Y%m%d)
          cat docker-compose.template|sed -e "s+{{IMAGE}}+synadia/nats-server:nightly-${NIGHTLY}+g" > docker-compose.yaml
          
          docker compose up -d

          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          VALIDATE_ONLY=1 ginkgo -v --keep-going -vet=off -r suites
